language: perl
perl:
  - "5.5.3"       # very ancient
  - "5.6.2"       # ancient
  - "5.8.8"       # common, prebuilt version
  - "5.8.8-thr"   # various build flags
  - "5.8.8-mb"
  - "5.8.8-dbg"
  - "5.8.8@moo"   # with local::lib
  - "5.17"        # older dev version
  - "5.17.11"     # will never be prebuilt
  - "5.18"        # existing perl version
  - 5.20          # work around lack of quoting
  - dev
matrix:
  include:
    - perl: "blead"
      env: VERBOSE=1
before_install:
  - source ./init
  - build-perl
  - perl -V
install: []
script:
  - prove -v
  - cpan-install git://github.com/travis-perl/TravisCI-Helpers-InstallerTest.git
  - perl -MTravisCI::Helpers::InstallerTest=master
  - cpan-install git://github.com/travis-perl/TravisCI-Helpers-InstallerTest.git@another-branch
  - perl -MTravisCI::Helpers::InstallerTest=another-branch
  - cpan-install Test::Spelling
  - which aspell
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
